# Generated by Django 5.2.5 on 2025-11-04 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Başlık')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('verified', models.BooleanField(default=False, verbose_name='Onaylandı mı?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Form',
                'verbose_name_plural': 'Formlar',
            },
        ),
        migrations.CreateModel(
            name='FormImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='form_images/', verbose_name='Form Resmi')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='forms.form')),
            ],
            options={
                'verbose_name': 'Form Resmi',
                'verbose_name_plural': 'Form Resimleri',
            },
        ),
    ]
