# Generated by Django 5.2.5 on 2025-09-25 11:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoilerBoardRepairer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='İsim')),
                ('business_type', models.CharField(max_length=50, verbose_name='İş Tipi')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adres')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Şehir')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Enlem')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Boylam')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-posta')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Web')),
                ('active', models.BooleanField(default=True, verbose_name='Gösterilsin mi?')),
            ],
        ),
        migrations.CreateModel(
            name='BoilerCardRepair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Video Linki')),
                ('active', models.BooleanField(default=True, verbose_name='Gösterilsin mi?')),
            ],
        ),
        migrations.CreateModel(
            name='BoilerRepairGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Yazı')),
                ('image', models.ImageField(blank=True, null=True, upload_to='boiler_repair_images/', verbose_name='Resim')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Video Linki')),
                ('active', models.BooleanField(default=True, verbose_name='Gösterilsin mi?')),
            ],
        ),
        migrations.CreateModel(
            name='BoilerWorkingPrinciple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('active', models.BooleanField(default=True, verbose_name='Gösterilsin mi?')),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Marka Adı')),
                ('image', models.ImageField(blank=True, null=True, upload_to='brand_images/', verbose_name='Marka Resmi')),
                ('active', models.BooleanField(default=True, verbose_name='Gösterilsin mi?')),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Yazı')),
                ('image', models.ImageField(blank=True, null=True, upload_to='instrument_usage_images/', verbose_name='Resim')),
                ('active', models.BooleanField(default=True, verbose_name='Gösterilsin mi?')),
            ],
        ),
        migrations.CreateModel(
            name='RoomTermostat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('image', models.ImageField(blank=True, null=True, upload_to='room_thermostat_images/', verbose_name='Resim')),
                ('active', models.BooleanField(default=True, verbose_name='Gösterilsin mi?')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tür Adı')),
                ('active', models.BooleanField(default=True, verbose_name='Gösterilsin mi?')),
            ],
        ),
        migrations.CreateModel(
            name='BoilerCardRepairImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='boiler_card_repair_images/', verbose_name='Resim')),
                ('active', models.BooleanField(default=True, verbose_name='Gösterilsin mi?')),
                ('boiler_card_repair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='faults.boilercardrepair')),
            ],
        ),
        migrations.AddField(
            model_name='boilercardrepair',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boiler_card_repairs', to='faults.brand'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Kategori Adı')),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images/', verbose_name='Kategori Resmi')),
                ('active', models.BooleanField(default=True, verbose_name='Gösterilsin mi?')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='faults.category')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='faults.type')),
            ],
        ),
        migrations.AddField(
            model_name='brand',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='faults.category'),
        ),
        migrations.AddField(
            model_name='boilercardrepair',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boiler_card_repairs', to='faults.category'),
        ),
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='Arıza Kodu')),
                ('image', models.ImageField(blank=True, null=True, upload_to='replaced_parts_images/', verbose_name='Değiştirilmesi Muhtemelen Parçalar')),
                ('fault_description', models.CharField(max_length=255, verbose_name='Arıza Tanımı')),
                ('possible_reasons', models.CharField(max_length=255, verbose_name='Muhtemel Nedenler')),
                ('technical_solution', models.CharField(max_length=255, verbose_name='Teknik Çözüm')),
                ('short_solution', models.CharField(max_length=255, verbose_name='Kısa Çözüm')),
                ('active', models.BooleanField(default=True, verbose_name='Gösterilsin mi?')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='faults.brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='faults.category')),
            ],
        ),
        migrations.CreateModel(
            name='ErrorSparePartImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='error_spare_part_pictures/', verbose_name='Yedek Parça Resmi')),
                ('active', models.BooleanField(default=True, verbose_name='Gösterilsin mi?')),
                ('error', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_spare_part_images', to='faults.error')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Model Adı')),
                ('image', models.ImageField(blank=True, null=True, upload_to='model_images/', verbose_name='Model Resmi')),
                ('active', models.BooleanField(default=True, verbose_name='Gösterilsin mi?')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='models', to='faults.brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='models', to='faults.category')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='models', to='faults.type')),
            ],
        ),
        migrations.AddField(
            model_name='error',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='faults.model'),
        ),
        migrations.AddField(
            model_name='boilercardrepair',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boiler_card_repairs', to='faults.model'),
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Parametre Adı')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('active', models.BooleanField(default=True, verbose_name='Gösterilsin mi?')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='faults.brand', verbose_name='paramaters')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='faults.category')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='faults.model')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='faults.type')),
            ],
        ),
        migrations.CreateModel(
            name='ParameterImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='parameter_images/', verbose_name='Parametre Resmi')),
                ('active', models.BooleanField(default=True, verbose_name='Gösterilsin mi?')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='faults.parameter')),
            ],
        ),
        migrations.CreateModel(
            name='SparePartsDefinitions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Parça Adı')),
                ('image', models.ImageField(blank=True, null=True, upload_to='spare_parts_definitions_images/', verbose_name='Parça Resmi')),
                ('what_is', models.TextField(blank=True, null=True, verbose_name='Ne İşe Yarar?')),
                ('how_works', models.TextField(blank=True, null=True, verbose_name='Nasıl çalışır?')),
                ('which_fault', models.TextField(blank=True, null=True, verbose_name='Hangi arıza ile ilgili?')),
                ('located', models.TextField(blank=True, null=True, verbose_name='Nerede bulunur?')),
                ('active', models.BooleanField(default=True, verbose_name='Gösterilsin mi?')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spare_parts_definitions', to='faults.brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spare_parts_definitions', to='faults.category')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spare_parts_definitions', to='faults.model')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spare_parts_definitions', to='faults.type')),
            ],
        ),
        migrations.AddField(
            model_name='error',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='faults.type'),
        ),
        migrations.AddField(
            model_name='brand',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='faults.type'),
        ),
        migrations.CreateModel(
            name='BoilerPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Parça Adı')),
                ('image', models.ImageField(blank=True, null=True, upload_to='boiler_part_images/', verbose_name='Parça Resmi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Ne İşe Yarar?')),
                ('active', models.BooleanField(default=True, verbose_name='Gösterilsin mi?')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boiler_parts', to='faults.brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boiler_parts', to='faults.category')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boiler_parts', to='faults.model')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boiler_parts', to='faults.type')),
            ],
        ),
        migrations.AddField(
            model_name='boilercardrepair',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boiler_card_repairs', to='faults.type'),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('video_url', models.URLField(verbose_name='Video Linki')),
                ('image', models.ImageField(blank=True, null=True, upload_to='video_images/', verbose_name='Resim')),
                ('active', models.BooleanField(default=True, verbose_name='Gösterilsin mi?')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='faults.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='faults.category')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='faults.model')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='faults.type')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='faults.brand')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_brands', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favori Marka',
                'verbose_name_plural': 'Favori Markalar',
                'unique_together': {('user', 'brand')},
            },
        ),
    ]
