# Generated by Django 5.2.9 on 2026-01-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faults', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boilerboardrepairer',
            name='business_type_ar',
            field=models.CharField(max_length=50, null=True, verbose_name='İş Tipi'),
        ),
        migrations.AddField(
            model_name='boilerboardrepairer',
            name='name_ar',
            field=models.CharField(max_length=150, null=True, verbose_name='İsim'),
        ),
        migrations.AddField(
            model_name='boilercardrepair',
            name='description_ar',
            field=models.TextField(null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='boilercardrepair',
            name='title_ar',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='boilerpart',
            name='name_ar',
            field=models.CharField(max_length=150, null=True, verbose_name='Parça Adı'),
        ),
        migrations.AddField(
            model_name='boilerrepairguide',
            name='content_ar',
            field=models.TextField(null=True, verbose_name='Yazı'),
        ),
        migrations.AddField(
            model_name='boilerrepairguide',
            name='title_ar',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='boilerworkingprinciple',
            name='description_ar',
            field=models.TextField(null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='boilerworkingprinciple',
            name='title_ar',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='brand',
            name='name_ar',
            field=models.CharField(max_length=100, null=True, verbose_name='Marka Adı'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ar',
            field=models.CharField(max_length=100, null=True, verbose_name='Kategori Adı'),
        ),
        migrations.AddField(
            model_name='faultcodes',
            name='code_ar',
            field=models.CharField(max_length=100, null=True, verbose_name='Arıza Kodu'),
        ),
        migrations.AddField(
            model_name='faultcodes',
            name='fault_description_ar',
            field=models.TextField(null=True, verbose_name='Arıza Tanımı'),
        ),
        migrations.AddField(
            model_name='instrumentusage',
            name='content_ar',
            field=models.TextField(null=True, verbose_name='Yazı'),
        ),
        migrations.AddField(
            model_name='instrumentusage',
            name='title_ar',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='model',
            name='name_ar',
            field=models.CharField(max_length=100, null=True, verbose_name='Model Adı'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='description_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='name_ar',
            field=models.CharField(max_length=150, null=True, verbose_name='Parametre Adı'),
        ),
        migrations.AddField(
            model_name='roomtermostat',
            name='description_ar',
            field=models.TextField(null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='roomtermostat',
            name='title_ar',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='sparepartimage',
            name='name_ar',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Yedek Parça Adı'),
        ),
        migrations.AddField(
            model_name='sparepartsdefinitions',
            name='description_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='sparepartsdefinitions',
            name='name_ar',
            field=models.CharField(max_length=150, null=True, verbose_name='Parça Adı'),
        ),
        migrations.AddField(
            model_name='video',
            name='description_ar',
            field=models.TextField(null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='video',
            name='title_ar',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlık'),
        ),
    ]
