# Generated by Django 5.2.5 on 2025-09-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faults', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='name_de',
            field=models.CharField(max_length=100, null=True, verbose_name='Marka Adı'),
        ),
        migrations.AddField(
            model_name='brand',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Marka Adı'),
        ),
        migrations.AddField(
            model_name='brand',
            name='name_es',
            field=models.CharField(max_length=100, null=True, verbose_name='Marka Adı'),
        ),
        migrations.AddField(
            model_name='brand',
            name='name_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='Marka Adı'),
        ),
        migrations.AddField(
            model_name='brand',
            name='name_it',
            field=models.CharField(max_length=100, null=True, verbose_name='Marka Adı'),
        ),
        migrations.AddField(
            model_name='brand',
            name='name_mk',
            field=models.CharField(max_length=100, null=True, verbose_name='Marka Adı'),
        ),
        migrations.AddField(
            model_name='brand',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Marka Adı'),
        ),
        migrations.AddField(
            model_name='brand',
            name='name_sq',
            field=models.CharField(max_length=100, null=True, verbose_name='Marka Adı'),
        ),
        migrations.AddField(
            model_name='brand',
            name='name_tr',
            field=models.CharField(max_length=100, null=True, verbose_name='Marka Adı'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_de',
            field=models.CharField(max_length=100, null=True, verbose_name='Kategori Adı'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Kategori Adı'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_es',
            field=models.CharField(max_length=100, null=True, verbose_name='Kategori Adı'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='Kategori Adı'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_it',
            field=models.CharField(max_length=100, null=True, verbose_name='Kategori Adı'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_mk',
            field=models.CharField(max_length=100, null=True, verbose_name='Kategori Adı'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Kategori Adı'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_sq',
            field=models.CharField(max_length=100, null=True, verbose_name='Kategori Adı'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_tr',
            field=models.CharField(max_length=100, null=True, verbose_name='Kategori Adı'),
        ),
        migrations.AddField(
            model_name='error',
            name='code_de',
            field=models.CharField(max_length=100, null=True, verbose_name='Arıza Kodu'),
        ),
        migrations.AddField(
            model_name='error',
            name='code_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Arıza Kodu'),
        ),
        migrations.AddField(
            model_name='error',
            name='code_es',
            field=models.CharField(max_length=100, null=True, verbose_name='Arıza Kodu'),
        ),
        migrations.AddField(
            model_name='error',
            name='code_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='Arıza Kodu'),
        ),
        migrations.AddField(
            model_name='error',
            name='code_it',
            field=models.CharField(max_length=100, null=True, verbose_name='Arıza Kodu'),
        ),
        migrations.AddField(
            model_name='error',
            name='code_mk',
            field=models.CharField(max_length=100, null=True, verbose_name='Arıza Kodu'),
        ),
        migrations.AddField(
            model_name='error',
            name='code_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Arıza Kodu'),
        ),
        migrations.AddField(
            model_name='error',
            name='code_sq',
            field=models.CharField(max_length=100, null=True, verbose_name='Arıza Kodu'),
        ),
        migrations.AddField(
            model_name='error',
            name='code_tr',
            field=models.CharField(max_length=100, null=True, verbose_name='Arıza Kodu'),
        ),
        migrations.AddField(
            model_name='error',
            name='fault_description_de',
            field=models.CharField(max_length=255, null=True, verbose_name='Arıza Tanımı'),
        ),
        migrations.AddField(
            model_name='error',
            name='fault_description_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Arıza Tanımı'),
        ),
        migrations.AddField(
            model_name='error',
            name='fault_description_es',
            field=models.CharField(max_length=255, null=True, verbose_name='Arıza Tanımı'),
        ),
        migrations.AddField(
            model_name='error',
            name='fault_description_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Arıza Tanımı'),
        ),
        migrations.AddField(
            model_name='error',
            name='fault_description_it',
            field=models.CharField(max_length=255, null=True, verbose_name='Arıza Tanımı'),
        ),
        migrations.AddField(
            model_name='error',
            name='fault_description_mk',
            field=models.CharField(max_length=255, null=True, verbose_name='Arıza Tanımı'),
        ),
        migrations.AddField(
            model_name='error',
            name='fault_description_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Arıza Tanımı'),
        ),
        migrations.AddField(
            model_name='error',
            name='fault_description_sq',
            field=models.CharField(max_length=255, null=True, verbose_name='Arıza Tanımı'),
        ),
        migrations.AddField(
            model_name='error',
            name='fault_description_tr',
            field=models.CharField(max_length=255, null=True, verbose_name='Arıza Tanımı'),
        ),
        migrations.AddField(
            model_name='error',
            name='possible_reasons_de',
            field=models.CharField(max_length=255, null=True, verbose_name='Muhtemel Nedenler'),
        ),
        migrations.AddField(
            model_name='error',
            name='possible_reasons_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Muhtemel Nedenler'),
        ),
        migrations.AddField(
            model_name='error',
            name='possible_reasons_es',
            field=models.CharField(max_length=255, null=True, verbose_name='Muhtemel Nedenler'),
        ),
        migrations.AddField(
            model_name='error',
            name='possible_reasons_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Muhtemel Nedenler'),
        ),
        migrations.AddField(
            model_name='error',
            name='possible_reasons_it',
            field=models.CharField(max_length=255, null=True, verbose_name='Muhtemel Nedenler'),
        ),
        migrations.AddField(
            model_name='error',
            name='possible_reasons_mk',
            field=models.CharField(max_length=255, null=True, verbose_name='Muhtemel Nedenler'),
        ),
        migrations.AddField(
            model_name='error',
            name='possible_reasons_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Muhtemel Nedenler'),
        ),
        migrations.AddField(
            model_name='error',
            name='possible_reasons_sq',
            field=models.CharField(max_length=255, null=True, verbose_name='Muhtemel Nedenler'),
        ),
        migrations.AddField(
            model_name='error',
            name='possible_reasons_tr',
            field=models.CharField(max_length=255, null=True, verbose_name='Muhtemel Nedenler'),
        ),
        migrations.AddField(
            model_name='error',
            name='short_solution_de',
            field=models.CharField(max_length=255, null=True, verbose_name='Kısa Çözüm'),
        ),
        migrations.AddField(
            model_name='error',
            name='short_solution_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Kısa Çözüm'),
        ),
        migrations.AddField(
            model_name='error',
            name='short_solution_es',
            field=models.CharField(max_length=255, null=True, verbose_name='Kısa Çözüm'),
        ),
        migrations.AddField(
            model_name='error',
            name='short_solution_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Kısa Çözüm'),
        ),
        migrations.AddField(
            model_name='error',
            name='short_solution_it',
            field=models.CharField(max_length=255, null=True, verbose_name='Kısa Çözüm'),
        ),
        migrations.AddField(
            model_name='error',
            name='short_solution_mk',
            field=models.CharField(max_length=255, null=True, verbose_name='Kısa Çözüm'),
        ),
        migrations.AddField(
            model_name='error',
            name='short_solution_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Kısa Çözüm'),
        ),
        migrations.AddField(
            model_name='error',
            name='short_solution_sq',
            field=models.CharField(max_length=255, null=True, verbose_name='Kısa Çözüm'),
        ),
        migrations.AddField(
            model_name='error',
            name='short_solution_tr',
            field=models.CharField(max_length=255, null=True, verbose_name='Kısa Çözüm'),
        ),
        migrations.AddField(
            model_name='error',
            name='technical_solution_de',
            field=models.CharField(max_length=255, null=True, verbose_name='Teknik Çözüm'),
        ),
        migrations.AddField(
            model_name='error',
            name='technical_solution_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Teknik Çözüm'),
        ),
        migrations.AddField(
            model_name='error',
            name='technical_solution_es',
            field=models.CharField(max_length=255, null=True, verbose_name='Teknik Çözüm'),
        ),
        migrations.AddField(
            model_name='error',
            name='technical_solution_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Teknik Çözüm'),
        ),
        migrations.AddField(
            model_name='error',
            name='technical_solution_it',
            field=models.CharField(max_length=255, null=True, verbose_name='Teknik Çözüm'),
        ),
        migrations.AddField(
            model_name='error',
            name='technical_solution_mk',
            field=models.CharField(max_length=255, null=True, verbose_name='Teknik Çözüm'),
        ),
        migrations.AddField(
            model_name='error',
            name='technical_solution_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Teknik Çözüm'),
        ),
        migrations.AddField(
            model_name='error',
            name='technical_solution_sq',
            field=models.CharField(max_length=255, null=True, verbose_name='Teknik Çözüm'),
        ),
        migrations.AddField(
            model_name='error',
            name='technical_solution_tr',
            field=models.CharField(max_length=255, null=True, verbose_name='Teknik Çözüm'),
        ),
        migrations.AddField(
            model_name='errorsparepartimage',
            name='image_de',
            field=models.ImageField(null=True, upload_to='error_spare_part_pictures/', verbose_name='Yedek Parça Resmi'),
        ),
        migrations.AddField(
            model_name='errorsparepartimage',
            name='image_en',
            field=models.ImageField(null=True, upload_to='error_spare_part_pictures/', verbose_name='Yedek Parça Resmi'),
        ),
        migrations.AddField(
            model_name='errorsparepartimage',
            name='image_es',
            field=models.ImageField(null=True, upload_to='error_spare_part_pictures/', verbose_name='Yedek Parça Resmi'),
        ),
        migrations.AddField(
            model_name='errorsparepartimage',
            name='image_fr',
            field=models.ImageField(null=True, upload_to='error_spare_part_pictures/', verbose_name='Yedek Parça Resmi'),
        ),
        migrations.AddField(
            model_name='errorsparepartimage',
            name='image_it',
            field=models.ImageField(null=True, upload_to='error_spare_part_pictures/', verbose_name='Yedek Parça Resmi'),
        ),
        migrations.AddField(
            model_name='errorsparepartimage',
            name='image_mk',
            field=models.ImageField(null=True, upload_to='error_spare_part_pictures/', verbose_name='Yedek Parça Resmi'),
        ),
        migrations.AddField(
            model_name='errorsparepartimage',
            name='image_ru',
            field=models.ImageField(null=True, upload_to='error_spare_part_pictures/', verbose_name='Yedek Parça Resmi'),
        ),
        migrations.AddField(
            model_name='errorsparepartimage',
            name='image_sq',
            field=models.ImageField(null=True, upload_to='error_spare_part_pictures/', verbose_name='Yedek Parça Resmi'),
        ),
        migrations.AddField(
            model_name='errorsparepartimage',
            name='image_tr',
            field=models.ImageField(null=True, upload_to='error_spare_part_pictures/', verbose_name='Yedek Parça Resmi'),
        ),
        migrations.AddField(
            model_name='model',
            name='name_de',
            field=models.CharField(max_length=100, null=True, verbose_name='Model Adı'),
        ),
        migrations.AddField(
            model_name='model',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Model Adı'),
        ),
        migrations.AddField(
            model_name='model',
            name='name_es',
            field=models.CharField(max_length=100, null=True, verbose_name='Model Adı'),
        ),
        migrations.AddField(
            model_name='model',
            name='name_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='Model Adı'),
        ),
        migrations.AddField(
            model_name='model',
            name='name_it',
            field=models.CharField(max_length=100, null=True, verbose_name='Model Adı'),
        ),
        migrations.AddField(
            model_name='model',
            name='name_mk',
            field=models.CharField(max_length=100, null=True, verbose_name='Model Adı'),
        ),
        migrations.AddField(
            model_name='model',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Model Adı'),
        ),
        migrations.AddField(
            model_name='model',
            name='name_sq',
            field=models.CharField(max_length=100, null=True, verbose_name='Model Adı'),
        ),
        migrations.AddField(
            model_name='model',
            name='name_tr',
            field=models.CharField(max_length=100, null=True, verbose_name='Model Adı'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='name_de',
            field=models.CharField(max_length=150, null=True, verbose_name='Parametre Adı'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Parametre Adı'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='name_es',
            field=models.CharField(max_length=150, null=True, verbose_name='Parametre Adı'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='name_fr',
            field=models.CharField(max_length=150, null=True, verbose_name='Parametre Adı'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='name_it',
            field=models.CharField(max_length=150, null=True, verbose_name='Parametre Adı'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='name_mk',
            field=models.CharField(max_length=150, null=True, verbose_name='Parametre Adı'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Parametre Adı'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='name_sq',
            field=models.CharField(max_length=150, null=True, verbose_name='Parametre Adı'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='name_tr',
            field=models.CharField(max_length=150, null=True, verbose_name='Parametre Adı'),
        ),
        migrations.AddField(
            model_name='type',
            name='name_de',
            field=models.CharField(max_length=100, null=True, verbose_name='Tür Adı'),
        ),
        migrations.AddField(
            model_name='type',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Tür Adı'),
        ),
        migrations.AddField(
            model_name='type',
            name='name_es',
            field=models.CharField(max_length=100, null=True, verbose_name='Tür Adı'),
        ),
        migrations.AddField(
            model_name='type',
            name='name_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='Tür Adı'),
        ),
        migrations.AddField(
            model_name='type',
            name='name_it',
            field=models.CharField(max_length=100, null=True, verbose_name='Tür Adı'),
        ),
        migrations.AddField(
            model_name='type',
            name='name_mk',
            field=models.CharField(max_length=100, null=True, verbose_name='Tür Adı'),
        ),
        migrations.AddField(
            model_name='type',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Tür Adı'),
        ),
        migrations.AddField(
            model_name='type',
            name='name_sq',
            field=models.CharField(max_length=100, null=True, verbose_name='Tür Adı'),
        ),
        migrations.AddField(
            model_name='type',
            name='name_tr',
            field=models.CharField(max_length=100, null=True, verbose_name='Tür Adı'),
        ),
    ]
