# Generated by Django 5.2.1 on 2026-04-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faults', '0002_boilerboardrepairer_business_type_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='main_page_order',
            field=models.IntegerField(default=0, verbose_name='Ana Sayfa Sırası'),
        ),
    ]
