# Generated by Django 5.2.5 on 2025-09-25 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faults', '0002_brand_name_de_brand_name_en_brand_name_es_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='name_mk',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='name_sq',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_mk',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_sq',
        ),
        migrations.RemoveField(
            model_name='error',
            name='code_mk',
        ),
        migrations.RemoveField(
            model_name='error',
            name='code_sq',
        ),
        migrations.RemoveField(
            model_name='error',
            name='fault_description_mk',
        ),
        migrations.RemoveField(
            model_name='error',
            name='fault_description_sq',
        ),
        migrations.RemoveField(
            model_name='error',
            name='possible_reasons_mk',
        ),
        migrations.RemoveField(
            model_name='error',
            name='possible_reasons_sq',
        ),
        migrations.RemoveField(
            model_name='error',
            name='short_solution_mk',
        ),
        migrations.RemoveField(
            model_name='error',
            name='short_solution_sq',
        ),
        migrations.RemoveField(
            model_name='error',
            name='technical_solution_mk',
        ),
        migrations.RemoveField(
            model_name='error',
            name='technical_solution_sq',
        ),
        migrations.RemoveField(
            model_name='errorsparepartimage',
            name='image_mk',
        ),
        migrations.RemoveField(
            model_name='errorsparepartimage',
            name='image_sq',
        ),
        migrations.RemoveField(
            model_name='model',
            name='name_mk',
        ),
        migrations.RemoveField(
            model_name='model',
            name='name_sq',
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='name_mk',
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='name_sq',
        ),
        migrations.RemoveField(
            model_name='type',
            name='name_mk',
        ),
        migrations.RemoveField(
            model_name='type',
            name='name_sq',
        ),
    ]
