# Generated by Django 5.2.5 on 2025-10-06 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faults', '0003_remove_brand_name_mk_remove_brand_name_sq_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='errorsparepartimage',
            name='image_de',
        ),
        migrations.RemoveField(
            model_name='errorsparepartimage',
            name='image_en',
        ),
        migrations.RemoveField(
            model_name='errorsparepartimage',
            name='image_es',
        ),
        migrations.RemoveField(
            model_name='errorsparepartimage',
            name='image_fr',
        ),
        migrations.RemoveField(
            model_name='errorsparepartimage',
            name='image_it',
        ),
        migrations.RemoveField(
            model_name='errorsparepartimage',
            name='image_ru',
        ),
        migrations.RemoveField(
            model_name='errorsparepartimage',
            name='image_tr',
        ),
        migrations.AddField(
            model_name='roomtermostat',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_thermostats', to='faults.brand'),
        ),
        migrations.AddField(
            model_name='roomtermostat',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_thermostats', to='faults.category'),
        ),
        migrations.AddField(
            model_name='roomtermostat',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_thermostats', to='faults.model'),
        ),
        migrations.AddField(
            model_name='roomtermostat',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_thermostats', to='faults.type'),
        ),
        migrations.AlterField(
            model_name='error',
            name='technical_solution',
            field=models.TextField(verbose_name='Teknik Çözüm'),
        ),
        migrations.AlterField(
            model_name='error',
            name='technical_solution_de',
            field=models.TextField(null=True, verbose_name='Teknik Çözüm'),
        ),
        migrations.AlterField(
            model_name='error',
            name='technical_solution_en',
            field=models.TextField(null=True, verbose_name='Teknik Çözüm'),
        ),
        migrations.AlterField(
            model_name='error',
            name='technical_solution_es',
            field=models.TextField(null=True, verbose_name='Teknik Çözüm'),
        ),
        migrations.AlterField(
            model_name='error',
            name='technical_solution_fr',
            field=models.TextField(null=True, verbose_name='Teknik Çözüm'),
        ),
        migrations.AlterField(
            model_name='error',
            name='technical_solution_it',
            field=models.TextField(null=True, verbose_name='Teknik Çözüm'),
        ),
        migrations.AlterField(
            model_name='error',
            name='technical_solution_ru',
            field=models.TextField(null=True, verbose_name='Teknik Çözüm'),
        ),
        migrations.AlterField(
            model_name='error',
            name='technical_solution_tr',
            field=models.TextField(null=True, verbose_name='Teknik Çözüm'),
        ),
    ]
