# Generated by Django 5.2.5 on 2025-10-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faults', '0004_remove_errorsparepartimage_image_de_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boilerboardrepairer',
            options={'verbose_name': '15-Kombi Kart Tamircisi', 'verbose_name_plural': '15-Kombi Kart Tamircileri'},
        ),
        migrations.AlterModelOptions(
            name='boilercardrepair',
            options={'verbose_name': '13-Kombi Kart Tamiri', 'verbose_name_plural': '13-Kombi Kart Tamiri'},
        ),
        migrations.AlterModelOptions(
            name='boilercardrepairimage',
            options={'verbose_name': '14-Kombi Kart Tamiri Resmi', 'verbose_name_plural': '14-Kombi Kart Tamiri Resimleri'},
        ),
        migrations.AlterModelOptions(
            name='boilerpart',
            options={'verbose_name': '10-Kombide Kullanılan Parça', 'verbose_name_plural': '10-Kombide Kullanılan Parçalar'},
        ),
        migrations.AlterModelOptions(
            name='boilerrepairguide',
            options={'verbose_name': '09-Kombi Tamiri Nasıl Yapılır', 'verbose_name_plural': '09-Kombi Tamiri Nasıl Yapılır'},
        ),
        migrations.AlterModelOptions(
            name='boilerworkingprinciple',
            options={'verbose_name': '12-Çalışma Prensibi', 'verbose_name_plural': '12-Çalışma Prensipleri'},
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': '03-Marka', 'verbose_name_plural': '03-Markalar'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '02-Kategori', 'verbose_name_plural': '02-Kategoriler'},
        ),
        migrations.AlterModelOptions(
            name='error',
            options={'verbose_name': '05-Arıza Kodu', 'verbose_name_plural': '05-Arıza Kodları'},
        ),
        migrations.AlterModelOptions(
            name='errorsparepartimage',
            options={'verbose_name': '06-Yedek Parça Resmi', 'verbose_name_plural': '06-Yedek Parça Resimleri'},
        ),
        migrations.AlterModelOptions(
            name='favoritebrand',
            options={'verbose_name': '19-Favori Marka', 'verbose_name_plural': '19-Favori Markalar'},
        ),
        migrations.AlterModelOptions(
            name='instrumentusage',
            options={'verbose_name': '16-Ölçü Aleti Kullanımı', 'verbose_name_plural': '16-Ölçü Aleti Kullanımı'},
        ),
        migrations.AlterModelOptions(
            name='model',
            options={'verbose_name': '04-Model', 'verbose_name_plural': '04-Modeller'},
        ),
        migrations.AlterModelOptions(
            name='parameter',
            options={'verbose_name': '07-Parametre', 'verbose_name_plural': '07-Parametreler'},
        ),
        migrations.AlterModelOptions(
            name='parameterimage',
            options={'verbose_name': '08-Parametre Resmi', 'verbose_name_plural': '08-Parametre Resimleri'},
        ),
        migrations.AlterModelOptions(
            name='roomtermostat',
            options={'verbose_name': '18-Oda Termosatları', 'verbose_name_plural': '18-Oda Termosatları'},
        ),
        migrations.AlterModelOptions(
            name='sparepartsdefinitions',
            options={'verbose_name': '11-Parça Tanıtımı', 'verbose_name_plural': '11-Parça Tanıtımı'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': '01-Tür', 'verbose_name_plural': '01-Türler'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': '17-Videolar', 'verbose_name_plural': '17-Videolar'},
        ),
        migrations.AddField(
            model_name='errorsparepartimage',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Yedek Parça Adı'),
        ),
    ]
