# Generated by Django 5.2.5 on 2025-10-11 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faults', '0005_alter_boilerboardrepairer_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='error',
            name='possible_reasons',
        ),
        migrations.RemoveField(
            model_name='error',
            name='possible_reasons_de',
        ),
        migrations.RemoveField(
            model_name='error',
            name='possible_reasons_en',
        ),
        migrations.RemoveField(
            model_name='error',
            name='possible_reasons_es',
        ),
        migrations.RemoveField(
            model_name='error',
            name='possible_reasons_fr',
        ),
        migrations.RemoveField(
            model_name='error',
            name='possible_reasons_it',
        ),
        migrations.RemoveField(
            model_name='error',
            name='possible_reasons_ru',
        ),
        migrations.RemoveField(
            model_name='error',
            name='possible_reasons_tr',
        ),
        migrations.RemoveField(
            model_name='error',
            name='short_solution',
        ),
        migrations.RemoveField(
            model_name='error',
            name='short_solution_de',
        ),
        migrations.RemoveField(
            model_name='error',
            name='short_solution_en',
        ),
        migrations.RemoveField(
            model_name='error',
            name='short_solution_es',
        ),
        migrations.RemoveField(
            model_name='error',
            name='short_solution_fr',
        ),
        migrations.RemoveField(
            model_name='error',
            name='short_solution_it',
        ),
        migrations.RemoveField(
            model_name='error',
            name='short_solution_ru',
        ),
        migrations.RemoveField(
            model_name='error',
            name='short_solution_tr',
        ),
        migrations.RemoveField(
            model_name='error',
            name='technical_solution_de',
        ),
        migrations.RemoveField(
            model_name='error',
            name='technical_solution_en',
        ),
        migrations.RemoveField(
            model_name='error',
            name='technical_solution_es',
        ),
        migrations.RemoveField(
            model_name='error',
            name='technical_solution_fr',
        ),
        migrations.RemoveField(
            model_name='error',
            name='technical_solution_it',
        ),
        migrations.RemoveField(
            model_name='error',
            name='technical_solution_ru',
        ),
        migrations.RemoveField(
            model_name='error',
            name='technical_solution_tr',
        ),
        migrations.CreateModel(
            name='PossibleReasons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Muhtemel Neden')),
                ('name_tr', models.CharField(max_length=100, null=True, verbose_name='Muhtemel Neden')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Muhtemel Neden')),
                ('name_de', models.CharField(max_length=100, null=True, verbose_name='Muhtemel Neden')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='Muhtemel Neden')),
                ('name_es', models.CharField(max_length=100, null=True, verbose_name='Muhtemel Neden')),
                ('name_it', models.CharField(max_length=100, null=True, verbose_name='Muhtemel Neden')),
                ('name_fr', models.CharField(max_length=100, null=True, verbose_name='Muhtemel Neden')),
                ('active', models.BooleanField(default=True, verbose_name='Gösterilsin mi?')),
                ('error', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='possible_reason_items', related_query_name='possible_reason', to='faults.error')),
            ],
            options={
                'verbose_name': 'Muhtemel Neden',
                'verbose_name_plural': 'Muhtemel Nedenler',
            },
        ),
        migrations.CreateModel(
            name='ShortSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kısa Çözüm')),
                ('name_tr', models.CharField(max_length=100, null=True, verbose_name='Kısa Çözüm')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Kısa Çözüm')),
                ('name_de', models.CharField(max_length=100, null=True, verbose_name='Kısa Çözüm')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='Kısa Çözüm')),
                ('name_es', models.CharField(max_length=100, null=True, verbose_name='Kısa Çözüm')),
                ('name_it', models.CharField(max_length=100, null=True, verbose_name='Kısa Çözüm')),
                ('name_fr', models.CharField(max_length=100, null=True, verbose_name='Kısa Çözüm')),
                ('active', models.BooleanField(default=True, verbose_name='Gösterilsin mi?')),
                ('error', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_solutions', to='faults.error')),
            ],
            options={
                'verbose_name': 'Kısa Çözüm',
                'verbose_name_plural': 'Kısa Çözümler',
            },
        ),
        migrations.CreateModel(
            name='TechnicalSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Teknik Çözüm')),
                ('name_tr', models.CharField(max_length=100, null=True, verbose_name='Teknik Çözüm')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Teknik Çözüm')),
                ('name_de', models.CharField(max_length=100, null=True, verbose_name='Teknik Çözüm')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='Teknik Çözüm')),
                ('name_es', models.CharField(max_length=100, null=True, verbose_name='Teknik Çözüm')),
                ('name_it', models.CharField(max_length=100, null=True, verbose_name='Teknik Çözüm')),
                ('name_fr', models.CharField(max_length=100, null=True, verbose_name='Teknik Çözüm')),
                ('active', models.BooleanField(default=True, verbose_name='Gösterilsin mi?')),
                ('error', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_solutions', to='faults.error')),
            ],
            options={
                'verbose_name': 'Teknik Çözüm',
                'verbose_name_plural': 'Teknik Çözümler',
            },
        ),
    ]
