# Generated by Django 5.2.5 on 2025-10-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faults', '0006_remove_error_possible_reasons_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='error',
            name='technical_solution_de',
            field=models.TextField(null=True, verbose_name='Teknik Çözüm'),
        ),
        migrations.AddField(
            model_name='error',
            name='technical_solution_en',
            field=models.TextField(null=True, verbose_name='Teknik Çözüm'),
        ),
        migrations.AddField(
            model_name='error',
            name='technical_solution_es',
            field=models.TextField(null=True, verbose_name='Teknik Çözüm'),
        ),
        migrations.AddField(
            model_name='error',
            name='technical_solution_fr',
            field=models.TextField(null=True, verbose_name='Teknik Çözüm'),
        ),
        migrations.AddField(
            model_name='error',
            name='technical_solution_it',
            field=models.TextField(null=True, verbose_name='Teknik Çözüm'),
        ),
        migrations.AddField(
            model_name='error',
            name='technical_solution_ru',
            field=models.TextField(null=True, verbose_name='Teknik Çözüm'),
        ),
        migrations.AddField(
            model_name='error',
            name='technical_solution_tr',
            field=models.TextField(null=True, verbose_name='Teknik Çözüm'),
        ),
    ]
