# Generated by Django 5.2.5 on 2025-10-31 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faults', '0007_error_technical_solution_de_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='error',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='error',
            name='category',
        ),
        migrations.RemoveField(
            model_name='error',
            name='model',
        ),
        migrations.RemoveField(
            model_name='error',
            name='type',
        ),
        migrations.RemoveField(
            model_name='possiblereasons',
            name='error',
        ),
        migrations.RemoveField(
            model_name='technicalsolution',
            name='error',
        ),
        migrations.RemoveField(
            model_name='shortsolution',
            name='error',
        ),
        migrations.RemoveField(
            model_name='roomtermostat',
            name='type',
        ),
        migrations.RemoveField(
            model_name='sparepartsdefinitions',
            name='type',
        ),
        migrations.RemoveField(
            model_name='video',
            name='type',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='type',
        ),
        migrations.RemoveField(
            model_name='category',
            name='type',
        ),
        migrations.RemoveField(
            model_name='model',
            name='type',
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='type',
        ),
        migrations.RemoveField(
            model_name='boilerpart',
            name='type',
        ),
        migrations.RemoveField(
            model_name='boilercardrepair',
            name='type',
        ),
        migrations.CreateModel(
            name='FaultCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='Arıza Kodu')),
                ('code_tr', models.CharField(max_length=100, null=True, verbose_name='Arıza Kodu')),
                ('code_en', models.CharField(max_length=100, null=True, verbose_name='Arıza Kodu')),
                ('code_de', models.CharField(max_length=100, null=True, verbose_name='Arıza Kodu')),
                ('code_ru', models.CharField(max_length=100, null=True, verbose_name='Arıza Kodu')),
                ('code_es', models.CharField(max_length=100, null=True, verbose_name='Arıza Kodu')),
                ('code_it', models.CharField(max_length=100, null=True, verbose_name='Arıza Kodu')),
                ('code_fr', models.CharField(max_length=100, null=True, verbose_name='Arıza Kodu')),
                ('fault_description', models.CharField(max_length=100, verbose_name='Arıza Tanımı')),
                ('fault_description_tr', models.CharField(max_length=100, null=True, verbose_name='Arıza Tanımı')),
                ('fault_description_en', models.CharField(max_length=100, null=True, verbose_name='Arıza Tanımı')),
                ('fault_description_de', models.CharField(max_length=100, null=True, verbose_name='Arıza Tanımı')),
                ('fault_description_ru', models.CharField(max_length=100, null=True, verbose_name='Arıza Tanımı')),
                ('fault_description_es', models.CharField(max_length=100, null=True, verbose_name='Arıza Tanımı')),
                ('fault_description_it', models.CharField(max_length=100, null=True, verbose_name='Arıza Tanımı')),
                ('fault_description_fr', models.CharField(max_length=100, null=True, verbose_name='Arıza Tanımı')),
                ('technical_solution', models.TextField(verbose_name='ileri Teknik Çözüm')),
                ('technical_solution_tr', models.TextField(null=True, verbose_name='ileri Teknik Çözüm')),
                ('technical_solution_en', models.TextField(null=True, verbose_name='ileri Teknik Çözüm')),
                ('technical_solution_de', models.TextField(null=True, verbose_name='ileri Teknik Çözüm')),
                ('technical_solution_ru', models.TextField(null=True, verbose_name='ileri Teknik Çözüm')),
                ('technical_solution_es', models.TextField(null=True, verbose_name='ileri Teknik Çözüm')),
                ('technical_solution_it', models.TextField(null=True, verbose_name='ileri Teknik Çözüm')),
                ('technical_solution_fr', models.TextField(null=True, verbose_name='ileri Teknik Çözüm')),
                ('possible_reasons', models.TextField(verbose_name='Muhtemel Nedenler')),
                ('short_solutions', models.TextField(verbose_name='Kısa Çözümler')),
                ('active', models.BooleanField(default=True, verbose_name='Gösterilsin mi?')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fault_codes', to='faults.brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fault_codes', to='faults.category')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fault_codes', to='faults.model')),
            ],
            options={
                'verbose_name': '05-Arıza Kodu',
                'verbose_name_plural': '05-Arıza Kodları',
            },
        ),
        migrations.CreateModel(
            name='SparePartImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Yedek Parça Adı')),
                ('name_tr', models.CharField(blank=True, max_length=100, null=True, verbose_name='Yedek Parça Adı')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Yedek Parça Adı')),
                ('name_de', models.CharField(blank=True, max_length=100, null=True, verbose_name='Yedek Parça Adı')),
                ('name_ru', models.CharField(blank=True, max_length=100, null=True, verbose_name='Yedek Parça Adı')),
                ('name_es', models.CharField(blank=True, max_length=100, null=True, verbose_name='Yedek Parça Adı')),
                ('name_it', models.CharField(blank=True, max_length=100, null=True, verbose_name='Yedek Parça Adı')),
                ('name_fr', models.CharField(blank=True, max_length=100, null=True, verbose_name='Yedek Parça Adı')),
                ('image', models.ImageField(upload_to='spare_part_pictures/', verbose_name='Yedek Parça Resmi')),
                ('active', models.BooleanField(default=True, verbose_name='Gösterilsin mi?')),
                ('fault_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spare_part_images', to='faults.faultcodes')),
            ],
            options={
                'verbose_name': '06-Yedek Parça Resmi',
                'verbose_name_plural': '06-Yedek Parça Resimleri',
            },
        ),
        migrations.DeleteModel(
            name='ErrorSparePartImage',
        ),
        migrations.DeleteModel(
            name='PossibleReasons',
        ),
        migrations.DeleteModel(
            name='TechnicalSolution',
        ),
        migrations.DeleteModel(
            name='Error',
        ),
        migrations.DeleteModel(
            name='ShortSolution',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
