# Generated by Django 5.2.5 on 2025-10-31 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faults', '0009_alter_brand_id_alter_model_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='model',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
