# Generated by Django 5.2.5 on 2025-10-31 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faults', '0010_alter_brand_id_alter_model_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='faultcodes',
            name='possible_reasons_de',
            field=models.TextField(null=True, verbose_name='Muhtemel Nedenler'),
        ),
        migrations.AddField(
            model_name='faultcodes',
            name='possible_reasons_en',
            field=models.TextField(null=True, verbose_name='Muhtemel Nedenler'),
        ),
        migrations.AddField(
            model_name='faultcodes',
            name='possible_reasons_es',
            field=models.TextField(null=True, verbose_name='Muhtemel Nedenler'),
        ),
        migrations.AddField(
            model_name='faultcodes',
            name='possible_reasons_fr',
            field=models.TextField(null=True, verbose_name='Muhtemel Nedenler'),
        ),
        migrations.AddField(
            model_name='faultcodes',
            name='possible_reasons_it',
            field=models.TextField(null=True, verbose_name='Muhtemel Nedenler'),
        ),
        migrations.AddField(
            model_name='faultcodes',
            name='possible_reasons_ru',
            field=models.TextField(null=True, verbose_name='Muhtemel Nedenler'),
        ),
        migrations.AddField(
            model_name='faultcodes',
            name='possible_reasons_tr',
            field=models.TextField(null=True, verbose_name='Muhtemel Nedenler'),
        ),
        migrations.AddField(
            model_name='faultcodes',
            name='short_solutions_de',
            field=models.TextField(null=True, verbose_name='Kısa Çözümler'),
        ),
        migrations.AddField(
            model_name='faultcodes',
            name='short_solutions_en',
            field=models.TextField(null=True, verbose_name='Kısa Çözümler'),
        ),
        migrations.AddField(
            model_name='faultcodes',
            name='short_solutions_es',
            field=models.TextField(null=True, verbose_name='Kısa Çözümler'),
        ),
        migrations.AddField(
            model_name='faultcodes',
            name='short_solutions_fr',
            field=models.TextField(null=True, verbose_name='Kısa Çözümler'),
        ),
        migrations.AddField(
            model_name='faultcodes',
            name='short_solutions_it',
            field=models.TextField(null=True, verbose_name='Kısa Çözümler'),
        ),
        migrations.AddField(
            model_name='faultcodes',
            name='short_solutions_ru',
            field=models.TextField(null=True, verbose_name='Kısa Çözümler'),
        ),
        migrations.AddField(
            model_name='faultcodes',
            name='short_solutions_tr',
            field=models.TextField(null=True, verbose_name='Kısa Çözümler'),
        ),
    ]
