# Generated by Django 5.2.5 on 2025-10-31 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faults', '0012_parameter_description_de_parameter_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boilerrepairguide',
            name='content_de',
            field=models.TextField(null=True, verbose_name='Yazı'),
        ),
        migrations.AddField(
            model_name='boilerrepairguide',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Yazı'),
        ),
        migrations.AddField(
            model_name='boilerrepairguide',
            name='content_es',
            field=models.TextField(null=True, verbose_name='Yazı'),
        ),
        migrations.AddField(
            model_name='boilerrepairguide',
            name='content_fr',
            field=models.TextField(null=True, verbose_name='Yazı'),
        ),
        migrations.AddField(
            model_name='boilerrepairguide',
            name='content_it',
            field=models.TextField(null=True, verbose_name='Yazı'),
        ),
        migrations.AddField(
            model_name='boilerrepairguide',
            name='content_ru',
            field=models.TextField(null=True, verbose_name='Yazı'),
        ),
        migrations.AddField(
            model_name='boilerrepairguide',
            name='content_tr',
            field=models.TextField(null=True, verbose_name='Yazı'),
        ),
    ]
