# Generated by Django 5.2.5 on 2025-10-31 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faults', '0013_boilerrepairguide_content_de_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boilerpart',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='Ne İşe Yarar?'),
        ),
        migrations.AddField(
            model_name='boilerpart',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Ne İşe Yarar?'),
        ),
        migrations.AddField(
            model_name='boilerpart',
            name='description_es',
            field=models.TextField(blank=True, null=True, verbose_name='Ne İşe Yarar?'),
        ),
        migrations.AddField(
            model_name='boilerpart',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Ne İşe Yarar?'),
        ),
        migrations.AddField(
            model_name='boilerpart',
            name='description_it',
            field=models.TextField(blank=True, null=True, verbose_name='Ne İşe Yarar?'),
        ),
        migrations.AddField(
            model_name='boilerpart',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Ne İşe Yarar?'),
        ),
        migrations.AddField(
            model_name='boilerpart',
            name='description_tr',
            field=models.TextField(blank=True, null=True, verbose_name='Ne İşe Yarar?'),
        ),
        migrations.AddField(
            model_name='boilerpart',
            name='name_de',
            field=models.CharField(max_length=150, null=True, verbose_name='Parça Adı'),
        ),
        migrations.AddField(
            model_name='boilerpart',
            name='name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Parça Adı'),
        ),
        migrations.AddField(
            model_name='boilerpart',
            name='name_es',
            field=models.CharField(max_length=150, null=True, verbose_name='Parça Adı'),
        ),
        migrations.AddField(
            model_name='boilerpart',
            name='name_fr',
            field=models.CharField(max_length=150, null=True, verbose_name='Parça Adı'),
        ),
        migrations.AddField(
            model_name='boilerpart',
            name='name_it',
            field=models.CharField(max_length=150, null=True, verbose_name='Parça Adı'),
        ),
        migrations.AddField(
            model_name='boilerpart',
            name='name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Parça Adı'),
        ),
        migrations.AddField(
            model_name='boilerpart',
            name='name_tr',
            field=models.CharField(max_length=150, null=True, verbose_name='Parça Adı'),
        ),
    ]
