# Generated by Django 5.2.5 on 2025-10-31 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faults', '0014_boilerpart_description_de_boilerpart_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparepartsdefinitions',
            name='how_works_de',
            field=models.TextField(blank=True, null=True, verbose_name='Nasıl çalışır?'),
        ),
        migrations.AddField(
            model_name='sparepartsdefinitions',
            name='how_works_en',
            field=models.TextField(blank=True, null=True, verbose_name='Nasıl çalışır?'),
        ),
        migrations.AddField(
            model_name='sparepartsdefinitions',
            name='how_works_es',
            field=models.TextField(blank=True, null=True, verbose_name='Nasıl çalışır?'),
        ),
        migrations.AddField(
            model_name='sparepartsdefinitions',
            name='how_works_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Nasıl çalışır?'),
        ),
        migrations.AddField(
            model_name='sparepartsdefinitions',
            name='how_works_it',
            field=models.TextField(blank=True, null=True, verbose_name='Nasıl çalışır?'),
        ),
        migrations.AddField(
            model_name='sparepartsdefinitions',
            name='how_works_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Nasıl çalışır?'),
        ),
        migrations.AddField(
            model_name='sparepartsdefinitions',
            name='how_works_tr',
            field=models.TextField(blank=True, null=True, verbose_name='Nasıl çalışır?'),
        ),
        migrations.AddField(
            model_name='sparepartsdefinitions',
            name='located_de',
            field=models.TextField(blank=True, null=True, verbose_name='Nerede bulunur?'),
        ),
        migrations.AddField(
            model_name='sparepartsdefinitions',
            name='located_en',
            field=models.TextField(blank=True, null=True, verbose_name='Nerede bulunur?'),
        ),
        migrations.AddField(
            model_name='sparepartsdefinitions',
            name='located_es',
            field=models.TextField(blank=True, null=True, verbose_name='Nerede bulunur?'),
        ),
        migrations.AddField(
            model_name='sparepartsdefinitions',
            name='located_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Nerede bulunur?'),
        ),
        migrations.AddField(
            model_name='sparepartsdefinitions',
            name='located_it',
            field=models.TextField(blank=True, null=True, verbose_name='Nerede bulunur?'),
        ),
        migrations.AddField(
            model_name='sparepartsdefinitions',
            name='located_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Nerede bulunur?'),
        ),
        migrations.AddField(
            model_name='sparepartsdefinitions',
            name='located_tr',
            field=models.TextField(blank=True, null=True, verbose_name='Nerede bulunur?'),
        ),
        migrations.AddField(
            model_name='sparepartsdefinitions',
            name='name_de',
            field=models.CharField(max_length=150, null=True, verbose_name='Parça Adı'),
        ),
        migrations.AddField(
            model_name='sparepartsdefinitions',
            name='name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Parça Adı'),
        ),
        migrations.AddField(
            model_name='sparepartsdefinitions',
            name='name_es',
            field=models.CharField(max_length=150, null=True, verbose_name='Parça Adı'),
        ),
        migrations.AddField(
            model_name='sparepartsdefinitions',
            name='name_fr',
            field=models.CharField(max_length=150, null=True, verbose_name='Parça Adı'),
        ),
        migrations.AddField(
            model_name='sparepartsdefinitions',
            name='name_it',
            field=models.CharField(max_length=150, null=True, verbose_name='Parça Adı'),
        ),
        migrations.AddField(
            model_name='sparepartsdefinitions',
            name='name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Parça Adı'),
        ),
        migrations.AddField(
            model_name='sparepartsdefinitions',
            name='name_tr',
            field=models.CharField(max_length=150, null=True, verbose_name='Parça Adı'),
        ),
        migrations.AddField(
            model_name='sparepartsdefinitions',
            name='what_is_de',
            field=models.TextField(blank=True, null=True, verbose_name='Ne İşe Yarar?'),
        ),
        migrations.AddField(
            model_name='sparepartsdefinitions',
            name='what_is_en',
            field=models.TextField(blank=True, null=True, verbose_name='Ne İşe Yarar?'),
        ),
        migrations.AddField(
            model_name='sparepartsdefinitions',
            name='what_is_es',
            field=models.TextField(blank=True, null=True, verbose_name='Ne İşe Yarar?'),
        ),
        migrations.AddField(
            model_name='sparepartsdefinitions',
            name='what_is_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Ne İşe Yarar?'),
        ),
        migrations.AddField(
            model_name='sparepartsdefinitions',
            name='what_is_it',
            field=models.TextField(blank=True, null=True, verbose_name='Ne İşe Yarar?'),
        ),
        migrations.AddField(
            model_name='sparepartsdefinitions',
            name='what_is_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Ne İşe Yarar?'),
        ),
        migrations.AddField(
            model_name='sparepartsdefinitions',
            name='what_is_tr',
            field=models.TextField(blank=True, null=True, verbose_name='Ne İşe Yarar?'),
        ),
        migrations.AddField(
            model_name='sparepartsdefinitions',
            name='which_fault_de',
            field=models.TextField(blank=True, null=True, verbose_name='Hangi arıza ile ilgili?'),
        ),
        migrations.AddField(
            model_name='sparepartsdefinitions',
            name='which_fault_en',
            field=models.TextField(blank=True, null=True, verbose_name='Hangi arıza ile ilgili?'),
        ),
        migrations.AddField(
            model_name='sparepartsdefinitions',
            name='which_fault_es',
            field=models.TextField(blank=True, null=True, verbose_name='Hangi arıza ile ilgili?'),
        ),
        migrations.AddField(
            model_name='sparepartsdefinitions',
            name='which_fault_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Hangi arıza ile ilgili?'),
        ),
        migrations.AddField(
            model_name='sparepartsdefinitions',
            name='which_fault_it',
            field=models.TextField(blank=True, null=True, verbose_name='Hangi arıza ile ilgili?'),
        ),
        migrations.AddField(
            model_name='sparepartsdefinitions',
            name='which_fault_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Hangi arıza ile ilgili?'),
        ),
        migrations.AddField(
            model_name='sparepartsdefinitions',
            name='which_fault_tr',
            field=models.TextField(blank=True, null=True, verbose_name='Hangi arıza ile ilgili?'),
        ),
    ]
