# Generated by Django 5.2.5 on 2025-10-31 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faults', '0017_boilercardrepair_description_de_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boilerboardrepairer',
            name='business_type_de',
            field=models.CharField(max_length=50, null=True, verbose_name='İş Tipi'),
        ),
        migrations.AddField(
            model_name='boilerboardrepairer',
            name='business_type_en',
            field=models.CharField(max_length=50, null=True, verbose_name='İş Tipi'),
        ),
        migrations.AddField(
            model_name='boilerboardrepairer',
            name='business_type_es',
            field=models.CharField(max_length=50, null=True, verbose_name='İş Tipi'),
        ),
        migrations.AddField(
            model_name='boilerboardrepairer',
            name='business_type_fr',
            field=models.CharField(max_length=50, null=True, verbose_name='İş Tipi'),
        ),
        migrations.AddField(
            model_name='boilerboardrepairer',
            name='business_type_it',
            field=models.CharField(max_length=50, null=True, verbose_name='İş Tipi'),
        ),
        migrations.AddField(
            model_name='boilerboardrepairer',
            name='business_type_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='İş Tipi'),
        ),
        migrations.AddField(
            model_name='boilerboardrepairer',
            name='business_type_tr',
            field=models.CharField(max_length=50, null=True, verbose_name='İş Tipi'),
        ),
        migrations.AddField(
            model_name='boilerboardrepairer',
            name='name_de',
            field=models.CharField(max_length=150, null=True, verbose_name='İsim'),
        ),
        migrations.AddField(
            model_name='boilerboardrepairer',
            name='name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='İsim'),
        ),
        migrations.AddField(
            model_name='boilerboardrepairer',
            name='name_es',
            field=models.CharField(max_length=150, null=True, verbose_name='İsim'),
        ),
        migrations.AddField(
            model_name='boilerboardrepairer',
            name='name_fr',
            field=models.CharField(max_length=150, null=True, verbose_name='İsim'),
        ),
        migrations.AddField(
            model_name='boilerboardrepairer',
            name='name_it',
            field=models.CharField(max_length=150, null=True, verbose_name='İsim'),
        ),
        migrations.AddField(
            model_name='boilerboardrepairer',
            name='name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='İsim'),
        ),
        migrations.AddField(
            model_name='boilerboardrepairer',
            name='name_tr',
            field=models.CharField(max_length=150, null=True, verbose_name='İsim'),
        ),
        migrations.AddField(
            model_name='instrumentusage',
            name='content_de',
            field=models.TextField(null=True, verbose_name='Yazı'),
        ),
        migrations.AddField(
            model_name='instrumentusage',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Yazı'),
        ),
        migrations.AddField(
            model_name='instrumentusage',
            name='content_es',
            field=models.TextField(null=True, verbose_name='Yazı'),
        ),
        migrations.AddField(
            model_name='instrumentusage',
            name='content_fr',
            field=models.TextField(null=True, verbose_name='Yazı'),
        ),
        migrations.AddField(
            model_name='instrumentusage',
            name='content_it',
            field=models.TextField(null=True, verbose_name='Yazı'),
        ),
        migrations.AddField(
            model_name='instrumentusage',
            name='content_ru',
            field=models.TextField(null=True, verbose_name='Yazı'),
        ),
        migrations.AddField(
            model_name='instrumentusage',
            name='content_tr',
            field=models.TextField(null=True, verbose_name='Yazı'),
        ),
        migrations.AddField(
            model_name='roomtermostat',
            name='description_de',
            field=models.TextField(null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='roomtermostat',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='roomtermostat',
            name='description_es',
            field=models.TextField(null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='roomtermostat',
            name='description_fr',
            field=models.TextField(null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='roomtermostat',
            name='description_it',
            field=models.TextField(null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='roomtermostat',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='roomtermostat',
            name='description_tr',
            field=models.TextField(null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='roomtermostat',
            name='title_de',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='roomtermostat',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='roomtermostat',
            name='title_es',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='roomtermostat',
            name='title_fr',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='roomtermostat',
            name='title_it',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='roomtermostat',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='roomtermostat',
            name='title_tr',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='video',
            name='description_de',
            field=models.TextField(null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='video',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='video',
            name='description_es',
            field=models.TextField(null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='video',
            name='description_fr',
            field=models.TextField(null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='video',
            name='description_it',
            field=models.TextField(null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='video',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='video',
            name='description_tr',
            field=models.TextField(null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='video',
            name='title_de',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='video',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='video',
            name='title_es',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='video',
            name='title_fr',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='video',
            name='title_it',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='video',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='video',
            name='title_tr',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlık'),
        ),
    ]
