# Generated by Django 5.2.5 on 2025-11-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faults', '0018_boilerboardrepairer_business_type_de_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faultcodes',
            name='fault_description',
            field=models.TextField(verbose_name='Arıza Tanımı'),
        ),
        migrations.AlterField(
            model_name='faultcodes',
            name='fault_description_de',
            field=models.TextField(null=True, verbose_name='Arıza Tanımı'),
        ),
        migrations.AlterField(
            model_name='faultcodes',
            name='fault_description_en',
            field=models.TextField(null=True, verbose_name='Arıza Tanımı'),
        ),
        migrations.AlterField(
            model_name='faultcodes',
            name='fault_description_es',
            field=models.TextField(null=True, verbose_name='Arıza Tanımı'),
        ),
        migrations.AlterField(
            model_name='faultcodes',
            name='fault_description_fr',
            field=models.TextField(null=True, verbose_name='Arıza Tanımı'),
        ),
        migrations.AlterField(
            model_name='faultcodes',
            name='fault_description_it',
            field=models.TextField(null=True, verbose_name='Arıza Tanımı'),
        ),
        migrations.AlterField(
            model_name='faultcodes',
            name='fault_description_ru',
            field=models.TextField(null=True, verbose_name='Arıza Tanımı'),
        ),
        migrations.AlterField(
            model_name='faultcodes',
            name='fault_description_tr',
            field=models.TextField(null=True, verbose_name='Arıza Tanımı'),
        ),
    ]
