# Generated by Django 5.2.5 on 2025-11-01 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faults', '0019_alter_faultcodes_fault_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(blank=True, choices=[('Arıza Kodu', 'Arıza Kodu'), ('Parametre', 'Parametre')], max_length=20, null=True, verbose_name='Kategori Tipi'),
        ),
    ]
