# Generated by Django 5.2.5 on 2025-11-02 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faults', '0020_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(blank=True, choices=[('Arıza Kodu', 'Arıza Kodu'), ('Parametre', 'Parametre'), ('Kombi Parçaları', 'Kombi Parçaları'), ('Parça Tanıtımları', 'Parça Tanıtımları'), ('Kombi Kart Tamiri', 'Kombi Kart Tamiri')], max_length=20, null=True, verbose_name='Kategori Tipi'),
        ),
        migrations.CreateModel(
            name='BoilerPartImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='boiler_part_images/', verbose_name='Parça Resmi')),
                ('active', models.BooleanField(default=True, verbose_name='Gösterilsin mi?')),
                ('boiler_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boiler_part_images', to='faults.boilerpart')),
            ],
            options={
                'verbose_name': '10-Kombide Kullanılan Parça Resmi',
                'verbose_name_plural': '10-Kombide Kullanılan Parça Resimleri',
            },
        ),
    ]
