# Generated by Django 5.2.5 on 2025-11-02 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faults', '0021_alter_category_type_boilerpartimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sparepartsdefinitions',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='sparepartsdefinitions',
            name='category',
        ),
        migrations.RemoveField(
            model_name='sparepartsdefinitions',
            name='image',
        ),
        migrations.RemoveField(
            model_name='sparepartsdefinitions',
            name='model',
        ),
        migrations.CreateModel(
            name='SparePartsDefinitionsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='spare_parts_definitions_images/', verbose_name='Parça Tanıtımı Resmi')),
                ('active', models.BooleanField(default=True, verbose_name='Gösterilsin mi?')),
                ('spare_parts_definitions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spare_parts_definitions_images', to='faults.sparepartsdefinitions')),
            ],
            options={
                'verbose_name': '11-Parça Tanıtımı Resmi',
                'verbose_name_plural': '11-Parça Tanıtımı Resimleri',
            },
        ),
    ]
