# Generated by Django 5.2.5 on 2025-11-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faults', '0022_remove_sparepartsdefinitions_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(blank=True, choices=[('Arıza Kodu', 'Arıza Kodu'), ('Parametre', 'Parametre'), ('Kombi Parçaları', 'Kombi Parçaları'), ('Kombi Kart Tamiri', 'Kombi Kart Tamiri')], max_length=20, null=True, verbose_name='Kategori Tipi'),
        ),
    ]
