# Generated by Django 5.2.5 on 2025-11-02 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faults', '0023_alter_category_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomtermostat',
            name='image',
        ),
        migrations.CreateModel(
            name='RoomTermostatImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='room_thermostat_images/', verbose_name='Resim')),
                ('active', models.BooleanField(default=True, verbose_name='Gösterilsin mi?')),
                ('room_thermostat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='faults.roomtermostat')),
            ],
            options={
                'verbose_name': '18-Oda Termosatları Resmi',
                'verbose_name_plural': '18-Oda Termosatları Resimleri',
            },
        ),
    ]
