# Generated by Django 5.2.5 on 2025-11-02 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faults', '0024_remove_roomtermostat_image_roomtermostatimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boilerpart',
            name='description',
        ),
        migrations.RemoveField(
            model_name='boilerpart',
            name='description_de',
        ),
        migrations.RemoveField(
            model_name='boilerpart',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='boilerpart',
            name='description_es',
        ),
        migrations.RemoveField(
            model_name='boilerpart',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='boilerpart',
            name='description_it',
        ),
        migrations.RemoveField(
            model_name='boilerpart',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='boilerpart',
            name='description_tr',
        ),
    ]
