# Generated by Django 5.2.5 on 2025-11-02 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faults', '0025_remove_boilerpart_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boilerpart',
            name='image',
        ),
    ]
