# Generated by Django 5.2.5 on 2025-11-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faults', '0026_remove_boilerpart_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boilerrepairguide',
            name='image',
        ),
        migrations.RemoveField(
            model_name='boilerrepairguide',
            name='video_url',
        ),
        migrations.AddField(
            model_name='boilerrepairguide',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Başlık'),
        ),
    ]
