# Generated by Django 5.2.5 on 2025-11-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faults', '0027_remove_boilerrepairguide_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentusage',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Başlık'),
        ),
    ]
