# Generated by Django 5.2.5 on 2025-11-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faults', '0028_instrumentusage_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boilerboardrepairer',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='boilerboardrepairer',
            name='longitude',
        ),
        migrations.AddField(
            model_name='boilerboardrepairer',
            name='location',
            field=models.TextField(blank=True, help_text='Google Maps embed iframe kodunu buraya yapıştırın', null=True),
        ),
    ]
