# Generated by Django 5.2.5 on 2025-11-03 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faults', '0029_remove_boilerboardrepairer_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Kategori')),
                ('image', models.ImageField(blank=True, null=True, upload_to='video_cateogry/', verbose_name='Resim')),
            ],
        ),
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='faults.videocategory'),
        ),
    ]
