# Generated by Django 5.2.5 on 2025-11-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faults', '0030_videocategory_alter_video_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocategory',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Gösterilsin mi?'),
        ),
    ]
