# Generated by Django 5.2.5 on 2025-11-03 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faults', '0031_videocategory_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='faults.category'),
        ),
        migrations.DeleteModel(
            name='VideoCategory',
        ),
    ]
