# Generated by Django 5.2.5 on 2025-11-03 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faults', '0032_alter_video_category_delete_videocategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(blank=True, choices=[('Arıza Kodu', 'Arıza Kodu'), ('Parametre', 'Parametre'), ('Kombi Parçaları', 'Kombi Parçaları'), ('Kombi Kart Tamiri', 'Kombi Kart Tamiri'), ('Video', 'Video'), ('Oda Termosatı', 'Oda Termosatı')], max_length=20, null=True, verbose_name='Kategori Tipi'),
        ),
        migrations.CreateModel(
            name='FavoriteFaultCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_fault_codes', to='faults.faultcodes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_fault_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '21-Favori Hata Kodu',
                'verbose_name_plural': '21-Favori Hata Kodları',
                'unique_together': {('user', 'fault')},
            },
        ),
        migrations.CreateModel(
            name='FavoriteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='faults.model')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_models', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '20-Favori Model',
                'verbose_name_plural': '20-Favori Model',
                'unique_together': {('user', 'model')},
            },
        ),
    ]
