# Generated by Django 5.2.5 on 2025-11-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faults', '0033_alter_category_type_favoritefaultcode_favoritemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentusage',
            name='title_de',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='instrumentusage',
            name='title_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='instrumentusage',
            name='title_es',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='instrumentusage',
            name='title_fr',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='instrumentusage',
            name='title_it',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='instrumentusage',
            name='title_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='instrumentusage',
            name='title_tr',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Başlık'),
        ),
    ]
