# Generated by Django 5.2.5 on 2025-11-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faults', '0034_instrumentusage_title_de_instrumentusage_title_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boilerrepairguide',
            name='title_de',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='boilerrepairguide',
            name='title_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='boilerrepairguide',
            name='title_es',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='boilerrepairguide',
            name='title_fr',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='boilerrepairguide',
            name='title_it',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='boilerrepairguide',
            name='title_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='boilerrepairguide',
            name='title_tr',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Başlık'),
        ),
    ]
