# Generated by Django 5.2.5 on 2025-11-05 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faults', '0035_boilerrepairguide_title_de_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faultcodes',
            name='possible_reasons',
        ),
        migrations.RemoveField(
            model_name='faultcodes',
            name='possible_reasons_de',
        ),
        migrations.RemoveField(
            model_name='faultcodes',
            name='possible_reasons_en',
        ),
        migrations.RemoveField(
            model_name='faultcodes',
            name='possible_reasons_es',
        ),
        migrations.RemoveField(
            model_name='faultcodes',
            name='possible_reasons_fr',
        ),
        migrations.RemoveField(
            model_name='faultcodes',
            name='possible_reasons_it',
        ),
        migrations.RemoveField(
            model_name='faultcodes',
            name='possible_reasons_ru',
        ),
        migrations.RemoveField(
            model_name='faultcodes',
            name='possible_reasons_tr',
        ),
        migrations.RemoveField(
            model_name='faultcodes',
            name='short_solutions',
        ),
        migrations.RemoveField(
            model_name='faultcodes',
            name='short_solutions_de',
        ),
        migrations.RemoveField(
            model_name='faultcodes',
            name='short_solutions_en',
        ),
        migrations.RemoveField(
            model_name='faultcodes',
            name='short_solutions_es',
        ),
        migrations.RemoveField(
            model_name='faultcodes',
            name='short_solutions_fr',
        ),
        migrations.RemoveField(
            model_name='faultcodes',
            name='short_solutions_it',
        ),
        migrations.RemoveField(
            model_name='faultcodes',
            name='short_solutions_ru',
        ),
        migrations.RemoveField(
            model_name='faultcodes',
            name='short_solutions_tr',
        ),
        migrations.RemoveField(
            model_name='faultcodes',
            name='technical_solution',
        ),
        migrations.RemoveField(
            model_name='faultcodes',
            name='technical_solution_de',
        ),
        migrations.RemoveField(
            model_name='faultcodes',
            name='technical_solution_en',
        ),
        migrations.RemoveField(
            model_name='faultcodes',
            name='technical_solution_es',
        ),
        migrations.RemoveField(
            model_name='faultcodes',
            name='technical_solution_fr',
        ),
        migrations.RemoveField(
            model_name='faultcodes',
            name='technical_solution_it',
        ),
        migrations.RemoveField(
            model_name='faultcodes',
            name='technical_solution_ru',
        ),
        migrations.RemoveField(
            model_name='faultcodes',
            name='technical_solution_tr',
        ),
    ]
