# Generated by Django 5.2.5 on 2025-11-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faults', '0036_remove_faultcodes_possible_reasons_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sparepartsdefinitions',
            name='how_works',
        ),
        migrations.RemoveField(
            model_name='sparepartsdefinitions',
            name='how_works_de',
        ),
        migrations.RemoveField(
            model_name='sparepartsdefinitions',
            name='how_works_en',
        ),
        migrations.RemoveField(
            model_name='sparepartsdefinitions',
            name='how_works_es',
        ),
        migrations.RemoveField(
            model_name='sparepartsdefinitions',
            name='how_works_fr',
        ),
        migrations.RemoveField(
            model_name='sparepartsdefinitions',
            name='how_works_it',
        ),
        migrations.RemoveField(
            model_name='sparepartsdefinitions',
            name='how_works_ru',
        ),
        migrations.RemoveField(
            model_name='sparepartsdefinitions',
            name='how_works_tr',
        ),
        migrations.RemoveField(
            model_name='sparepartsdefinitions',
            name='located',
        ),
        migrations.RemoveField(
            model_name='sparepartsdefinitions',
            name='located_de',
        ),
        migrations.RemoveField(
            model_name='sparepartsdefinitions',
            name='located_en',
        ),
        migrations.RemoveField(
            model_name='sparepartsdefinitions',
            name='located_es',
        ),
        migrations.RemoveField(
            model_name='sparepartsdefinitions',
            name='located_fr',
        ),
        migrations.RemoveField(
            model_name='sparepartsdefinitions',
            name='located_it',
        ),
        migrations.RemoveField(
            model_name='sparepartsdefinitions',
            name='located_ru',
        ),
        migrations.RemoveField(
            model_name='sparepartsdefinitions',
            name='located_tr',
        ),
        migrations.RemoveField(
            model_name='sparepartsdefinitions',
            name='what_is',
        ),
        migrations.RemoveField(
            model_name='sparepartsdefinitions',
            name='what_is_de',
        ),
        migrations.RemoveField(
            model_name='sparepartsdefinitions',
            name='what_is_en',
        ),
        migrations.RemoveField(
            model_name='sparepartsdefinitions',
            name='what_is_es',
        ),
        migrations.RemoveField(
            model_name='sparepartsdefinitions',
            name='what_is_fr',
        ),
        migrations.RemoveField(
            model_name='sparepartsdefinitions',
            name='what_is_it',
        ),
        migrations.RemoveField(
            model_name='sparepartsdefinitions',
            name='what_is_ru',
        ),
        migrations.RemoveField(
            model_name='sparepartsdefinitions',
            name='what_is_tr',
        ),
        migrations.RemoveField(
            model_name='sparepartsdefinitions',
            name='which_fault',
        ),
        migrations.RemoveField(
            model_name='sparepartsdefinitions',
            name='which_fault_de',
        ),
        migrations.RemoveField(
            model_name='sparepartsdefinitions',
            name='which_fault_en',
        ),
        migrations.RemoveField(
            model_name='sparepartsdefinitions',
            name='which_fault_es',
        ),
        migrations.RemoveField(
            model_name='sparepartsdefinitions',
            name='which_fault_fr',
        ),
        migrations.RemoveField(
            model_name='sparepartsdefinitions',
            name='which_fault_it',
        ),
        migrations.RemoveField(
            model_name='sparepartsdefinitions',
            name='which_fault_ru',
        ),
        migrations.RemoveField(
            model_name='sparepartsdefinitions',
            name='which_fault_tr',
        ),
        migrations.AddField(
            model_name='sparepartsdefinitions',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='sparepartsdefinitions',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='sparepartsdefinitions',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='sparepartsdefinitions',
            name='description_es',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='sparepartsdefinitions',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='sparepartsdefinitions',
            name='description_it',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='sparepartsdefinitions',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='sparepartsdefinitions',
            name='description_tr',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
    ]
