# Generated by Django 5.2.5 on 2025-11-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faults', '0037_remove_sparepartsdefinitions_how_works_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faultcodes',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='fault_codes_images/', verbose_name='Arıza Kodu Resmi'),
        ),
    ]
