# Generated by Django 5.2.1 on 2026-05-02 13:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='first_membership_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='İlk Üyelik Tarihi'),
        ),
        migrations.AddField(
            model_name='company',
            name='renewal_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Yenileme Sayısı'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_membership_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='İlk Üyelik Tarihi'),
        ),
        migrations.AddField(
            model_name='user',
            name='renewal_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Yenileme Sayısı'),
        ),
        migrations.CreateModel(
            name='MembershipHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Dönem Başlangıcı')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Dönem Bitişi')),
                ('renewal_number', models.PositiveIntegerField(verbose_name='Kaçıncı Yenileme')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membership_history', to='accounts.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membership_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Üyelik Geçmişi',
                'verbose_name_plural': 'Üyelik Geçmişleri',
                'ordering': ['-start_date'],
            },
        ),
    ]
