# Generated by Django 5.2.5 on 2025-09-12 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_defineddevice_price_de_defineddevice_price_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defineddevice',
            options={'verbose_name_plural': 'Tanımlı Cihazlar'},
        ),
        migrations.AlterModelOptions(
            name='pushdevice',
            options={'ordering': ['-updated_at'], 'verbose_name_plural': 'Bildirim Tokenları'},
        ),
        migrations.RemoveField(
            model_name='defineddevice',
            name='discount_percent',
        ),
        migrations.RemoveField(
            model_name='defineddevice',
            name='price',
        ),
        migrations.RemoveField(
            model_name='defineddevice',
            name='price_de',
        ),
        migrations.RemoveField(
            model_name='defineddevice',
            name='price_en',
        ),
        migrations.RemoveField(
            model_name='defineddevice',
            name='price_es',
        ),
        migrations.RemoveField(
            model_name='defineddevice',
            name='price_fr',
        ),
        migrations.RemoveField(
            model_name='defineddevice',
            name='price_it',
        ),
        migrations.RemoveField(
            model_name='defineddevice',
            name='price_mk',
        ),
        migrations.RemoveField(
            model_name='defineddevice',
            name='price_ru',
        ),
        migrations.RemoveField(
            model_name='defineddevice',
            name='price_sq',
        ),
        migrations.RemoveField(
            model_name='defineddevice',
            name='price_tr',
        ),
    ]
