# Generated by Django 5.2.1 on 2026-05-02 13:04

from django.db import migrations


def migrate_existing_data(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    Company = apps.get_model('accounts', 'Company')
    MembershipHistory = apps.get_model('accounts', 'MembershipHistory')

    # Update Users
    for user in User.objects.filter(membership_status='PREMIUM', membership_created_at__isnull=False):
        user.first_membership_date = user.membership_created_at
        user.renewal_count = 1
        user.save(update_fields=['first_membership_date', 'renewal_count'])
        MembershipHistory.objects.create(
            user=user,
            start_date=user.membership_created_at,
            end_date=user.membership_expires_at,
            renewal_number=1
        )

    # Update Companies
    for company in Company.objects.filter(membership_created_at__isnull=False):
        company.first_membership_date = company.membership_created_at
        company.renewal_count = 1
        company.save(update_fields=['first_membership_date', 'renewal_count'])
        MembershipHistory.objects.create(
            company=company,
            start_date=company.membership_created_at,
            end_date=company.membership_expires_at,
            renewal_number=1
        )

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_company_first_membership_date_company_renewal_count_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_existing_data),
    ]
