# Generated by Django 5.2.5 on 2025-09-12 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_defineddevice_options_alter_pushdevice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='membership_type',
            field=models.CharField(blank=True, choices=[('INDIVIDUAL', 'Individual'), ('CORPORATE', 'Corporate')], default='INDIVIDUAL', max_length=50, null=True, verbose_name='Üyelik Türü'),
        ),
    ]
