# Generated by Django 5.2.1 on 2026-05-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_migrate_existing_memberships'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_used_trial',
            field=models.BooleanField(default=False, verbose_name='3 Günlük Deneme Kullandı'),
        ),
        migrations.AddField(
            model_name='user',
            name='trial_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deneme Başlangıç Tarihi'),
        ),
    ]
