# Generated by Django 5.2.5 on 2025-09-13 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_membership_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='device_renewals_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='device_renewals_code_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'This email address is already registered'}, max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='DeviceRenewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(blank=True, max_length=50, null=True)),
                ('device_info', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_renewals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Cihaz Yenilemeleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
