# Generated by Django 5.2.5 on 2025-09-13 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_device_renewals_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='device_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
