# Generated by Django 5.2.5 on 2025-09-14 10:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_device_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defineddevice',
            options={'ordering': ['-last_used'], 'verbose_name_plural': 'Tanımlı Cihazlar'},
        ),
        migrations.AddField(
            model_name='defineddevice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='defineddevice',
            name='last_used',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='defineddevice',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Cihazın bağlı olduğu şirket (opsiyonel, bireysel üyeliklerde boş kalabilir)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_defined_devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='defineddevice',
            name='device_id',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Tanımlı Cihaz'),
        ),
        migrations.AlterField(
            model_name='defineddevice',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='defineddevice',
            name='max_users',
            field=models.PositiveIntegerField(default=5, help_text='Bu organizasyonda izin verilen maksimum aktif kullanıcı sayısı'),
        ),
        migrations.AlterField(
            model_name='defineddevice',
            name='user',
            field=models.ForeignKey(help_text='Bu cihazı kullanan kullanıcı', on_delete=django.db.models.deletion.CASCADE, related_name='user_defined_devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='membership_type',
            field=models.CharField(blank=True, choices=[('INDIVIDUAL', 'Bireysel'), ('TEAM', 'Takım'), ('ENTERPRISE', 'Kurumsal')], default='INDIVIDUAL', max_length=50, null=True, verbose_name='Üyelik Türü'),
        ),
        migrations.AlterUniqueTogether(
            name='defineddevice',
            unique_together={('company', 'device_id')},
        ),
    ]
