# Generated by Django 5.2.5 on 2025-09-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_defineddevice_options_defineddevice_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defineddevice',
            name='last_used',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
