# Generated by Django 5.2.5 on 2025-09-14 20:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_defineddevice_last_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defineddevice',
            name='max_users',
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=50)),
                ('max_users', models.PositiveIntegerField(default=5, help_text='Bu organizasyonda izin verilen maksimum aktif kullanıcı sayısı')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_used', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='defineddevice',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Cihazın bağlı olduğu şirket (opsiyonel, bireysel üyeliklerde boş kalabilir)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_defined_devices', to='accounts.company'),
        ),
    ]
