# Generated by Django 5.2.5 on 2025-09-15 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_defineddevice_max_users_company_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Şirketler'},
        ),
        migrations.AlterField(
            model_name='defineddevice',
            name='company',
            field=models.ForeignKey(help_text='Cihazın bağlı olduğu şirket (opsiyonel, bireysel üyeliklerde boş kalabilir)', on_delete=django.db.models.deletion.CASCADE, related_name='company_defined_devices', to='accounts.company'),
        ),
    ]
