# Generated by Django 5.2 on 2025-10-01 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_company_options_alter_defineddevice_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defineddevice',
            name='company',
            field=models.ForeignKey(help_text='Cihazın bağlı olduğu şirket', on_delete=django.db.models.deletion.CASCADE, related_name='company_defined_devices', to='accounts.company'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('REGISTER', 'Register'), ('PASSWORD_CHANGE', 'Password Change'), ('PASSWORD_RESET', 'Password Reset'), ('DEVICE_CHANGE', 'Device Change'), ('EMAIL_VERIFY', 'Email Verify'), ('PROFILE_UPDATE', 'Profile Update'), ('FAILED_LOGIN', 'Failed Login')], max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, help_text='Ek detaylar JSON formatında', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='accounts_au_created_721afe_idx'), models.Index(fields=['user', '-created_at'], name='accounts_au_user_id_14f360_idx'), models.Index(fields=['action', '-created_at'], name='accounts_au_action_f18cdc_idx')],
            },
        ),
    ]
