# Generated by Django 5.2.5 on 2025-10-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_defineddevice_company_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='membership_type',
            field=models.CharField(blank=True, choices=[('INDIVIDUAL', 'Individual'), ('TEAM', 'Team'), ('ENTERPRISE', 'Corporate')], default='INDIVIDUAL', max_length=50, null=True, verbose_name='Üyelik Türü'),
        ),
    ]
