# Generated by Django 5.2.5 on 2025-10-27 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_expopushtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='last_used',
        ),
        migrations.AddField(
            model_name='company',
            name='password',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='membership_status',
            field=models.CharField(blank=True, choices=[('FREE', 'Free'), ('PREMIUM', 'Premium')], default='FREE', max_length=50, null=True, verbose_name='Üyelik Durumu'),
        ),
        migrations.AlterField(
            model_name='user',
            name='membership_type',
            field=models.CharField(blank=True, choices=[('INDIVIDUAL', 'Individual'), ('TEAM', 'Team')], default='INDIVIDUAL', max_length=50, null=True, verbose_name='Üyelik Türü'),
        ),
    ]
