# Generated by Django 5.2.5 on 2025-10-27 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_company_last_used_company_password_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defineddevice',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Tanımlı Cihazlar'},
        ),
        migrations.AlterUniqueTogether(
            name='defineddevice',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='defineddevice',
            name='last_used',
        ),
    ]
