# Generated by Django 5.2.5 on 2025-10-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_defineddevice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='membership_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='membership_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
