# Generated by Django 5.2.5 on 2025-10-31 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_company_membership_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PushDevice',
        ),
    ]
