# Generated by Django 5.2.5 on 2025-12-25 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IbanNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iban', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_tr', models.CharField(max_length=100, null=True)),
                ('title_en', models.CharField(max_length=100, null=True)),
                ('title_de', models.CharField(max_length=100, null=True)),
                ('title_ru', models.CharField(max_length=100, null=True)),
                ('title_es', models.CharField(max_length=100, null=True)),
                ('title_it', models.CharField(max_length=100, null=True)),
                ('title_fr', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('TEAM', 'Team')], default='INDIVIDUAL', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('description_tr', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('description_de', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
                ('description_es', models.TextField(null=True)),
                ('description_it', models.TextField(null=True)),
                ('description_fr', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': '01-Ürünler',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PAYMENT', 'Ödeme'), ('SUBSCRIPTION', 'Abone'), ('CREDIT_CARD', 'Kredi Kartı'), ('EFT_TRANSFER', 'EFT&Transfer')], default='CREDIT_CARD', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.product')),
            ],
            options={
                'verbose_name_plural': 'Ödemeler',
            },
        ),
        migrations.CreateModel(
            name='OrderNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('order_number', models.CharField(max_length=6)),
                ('status', models.CharField(choices=[('PENDING', 'Bekliyor'), ('COMPLETED', 'Tamamlandı'), ('CANCELLED', 'İptal Edildi')], default='PENDING', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.product')),
            ],
            options={
                'verbose_name_plural': 'Sipariş Bildirimleri',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('number', models.CharField(max_length=6)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.payment')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.product')),
            ],
            options={
                'verbose_name_plural': 'Siparişler',
            },
        ),
    ]
