# Generated by Django 5.2.5 on 2025-11-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Ürün', 'verbose_name_plural': '01-Ürünler'},
        ),
        migrations.AddField(
            model_name='product',
            name='description_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_it',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_it',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_tr',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
