# Generated by Django 5.2.5 on 2025-11-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_product_options_product_description_de_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordernotification',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
