# Generated by Django 5.2.5 on 2025-11-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_ordernotification_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordernotification',
            name='verified',
        ),
        migrations.AddField(
            model_name='ordernotification',
            name='status',
            field=models.CharField(choices=[('Bekliyor', 'Bekliyor'), ('Tamamlandı', 'Bekliyor'), ('İptal Edildi', 'Bekliyor')], default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('Ödeme', 'Ödeme'), ('Abone', 'Abone'), ('Kredi Kartı', 'Kredi Kartı'), ('EFT&TRANSFER', 'EFT&Transfer')], default='CREDIT_CARD', max_length=50),
        ),
    ]
