# Generated by Django 5.2.5 on 2025-11-13 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_ordernotification_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordernotification',
            name='status',
            field=models.CharField(choices=[('Bekliyor', 'Bekliyor'), ('Tamamlandı', 'Tamamlandı'), ('İptal Edildi', 'İptal Edildi')], default='PENDING', max_length=50),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
