# Generated by Django 5.2.5 on 2025-11-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_remove_payment_quantity_order_total_price_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IbanNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("iban", models.CharField(blank=True, max_length=100, null=True)),
                ("description", models.TextField()),
            ],
        ),
    ]
