# Generated by Django 5.2.5 on 2025-11-17 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_payment_quantity_order_total_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('TRY', 'Türk Lirası'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('RUB', 'Russian Ruble'), ('EUR_TRY', 'Euro (Türkiye)')], default='TRY', max_length=10, verbose_name='Para Birimi')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fiyat')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='İndirimli Fiyat')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='orders.product', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Ürün Fiyatı',
                'verbose_name_plural': '02-Ürün Fiyatları',
                'unique_together': {('product', 'currency')},
            },
        ),
    ]
