# Generated by Django 5.2.5 on 2025-11-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_productprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='IbanNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='ProductPrice',
        ),
    ]
