# Generated by Django 5.2.5 on 2025-11-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_ibannumber_delete_productprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='ibannumber',
            name='iban',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
