# Generated by Django 5.2.5 on 2025-11-17 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_ibannumber_iban'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordernotification',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Bekliyor'), ('COMPLETED', 'Tamamlandı'), ('CANCELLED', 'İptal Edildi')], default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('PAYMENT', 'Ödeme'), ('SUBSCRIPTION', 'Abone'), ('CREDIT_CARD', 'Kredi Kartı'), ('EFT_TRANSFER', 'EFT&Transfer')], default='CREDIT_CARD', max_length=50),
        ),
    ]
